# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cateringmenu',
            name='flavors',
        ),
        migrations.AddField(
            model_name='cateringmenu',
            name='flavors',
            field=models.ManyToManyField(to='orders.Flavor'),
        ),
    ]
