# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170411_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.AlterField(
            model_name='cateringmenu',
            name='date_created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='date_added',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='flavors',
            field=models.ManyToManyField(to='orders.Flavor'),
        ),
    ]
