# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20170426_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cateringmenu',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddField(
            model_name='flavor',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='flavor_name',
            field=models.CharField(max_length=50),
        ),
    ]
