# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20170501_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cateringmenu',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cateringmenu',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
