# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyCal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='locationName',
            field=models.CharField(default='none', max_length=30),
            preserve_default=False,
        ),
    ]
