# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyCal', '0002_time_locationname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Time',
        ),
        migrations.AddField(
            model_name='location',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='location',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='location',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
