# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyCal', '0003_auto_20170424_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('end_time', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='date',
        ),
        migrations.RemoveField(
            model_name='location',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='location',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weeklyCal.Location'),
        ),
    ]
